### ISSUE TITLE
Kann es lokal nicht starten

### ISSUE THREAD

**Issue by pascalfiv** [NinoHelfenstein/M293-Zoo-per#4]
Bei mir sieht das ganze dann so aus, wenn ich index.html im Chrome öffne.
<img width="1398" alt="image" src="https://github.com/NinoHelfenstein/M293-Zoo-per/assets/11438750/c1199803-4696-437f-b74a-9501ef1f9ddb">

**Comment by NinoHelfenstein** [comment]
@pascalfiv pull again and try it please ^^

**Comment by pascalfiv** [comment]
Bilder funktionieren noch nicht...

**Comment by NinoHelfenstein** [comment]
jetzt?
